### ISSUE TITLE
💡Just an idea 

### ISSUE THREAD

**Issue by inikolaev** [xdanny/pyspark_types#1]
Maybe you can get inspiration from `pydantic` and define models that can be converted to PySpark struct, e.g. something like

```python
class Person(PySparkModel):
    name: str 
    age: int
    is_student: bool
    optional: Optional[str]
```

Then you would create it as any other data class

```python
person = Person(name="Scott", age=30, is_student=False)
spark_struct = person.struct()
```

It might be possible to implement it on top of pydantic as well, but create a separate base class derived from `BaseModel` which would define extra methods to convert to PySpark struct.

I think you pretty much have all the mechanics done. Unless of course it's easier to work with data classes as is and do conversion separately.

**Comment by xdanny** [comment]
That's a great idea @inikolaev, I think this will improve the data generation to unit test pyspark functions. I created a PR https://github.com/xdanny/pyspark_types/pull/2, feel free to check.
